import Header from "@/app/components/header/header";
import Footer from "@/app/components/footer/footer";
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import {ContextProvider} from "./context/context.jsx";
import './globals.css';
import Home from "@/app/page";
import WhatsApp from "@/app/components/whatsApp/whatsApp";
import "./reset.css";
import Navbar from "@/app/components/header/navbar/navbar";


export const metadata = {
    title: 'Next.js', description: 'Generated by Next.js',
}

export default function RootLayout() {
    return (
        <html lang="en">
        <ContextProvider>
            <body>
            <Navbar/>
            <Header/>
            <Home/>
            <WhatsApp/>
            <Footer/>
            </body>
        </ContextProvider>
        </html>
    )
}
